DROP TABLE IF EXISTS sellercategory;
DROP TABLE IF EXISTS sellers;
DROP TABLE IF EXISTS goodscategoryleveltwo;
DROP TABLE IF EXISTS goodscategorylevelone;
DROP TABLE IF EXISTS mainconf;

CREATE TABLE mainconf (
    PK INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(20) NOT NULL,
    PAGE_LOAD_INTERVAL INT NOT NULL,
    CACHE_SIZE INT NOT NULL,
    ITEM_LIMIT INT NOT NULL,
    FLAG_PAUSE BOOLEAN NOT NULL
) ENGINE = INNODB, COLLATE = utf8_general_ci;

INSERT INTO mainconf (PK, TITLE, PAGE_LOAD_INTERVAL, CACHE_SIZE, ITEM_LIMIT, FLAG_PAUSE) VALUES
(1, 'Default', 1, 100, 10000, TRUE);

CREATE TABLE goodscategorylevelone (
    PK INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(64) NOT NULL
) ENGINE = INNODB, COLLATE = utf8_general_ci;

CREATE TABLE goodscategoryleveltwo (
    PK INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SUB_HEADING INT UNSIGNED NOT NULL,
    TITLE VARCHAR(64) NOT NULL,
    FOREIGN KEY (SUB_HEADING) REFERENCES goodscategorylevelone(PK) ON UPDATE CASCADE
) ENGINE = INNODB, COLLATE = utf8_general_ci;

CREATE TABLE sellers (
    PK INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(64) NOT NULL ,
    SCORE INT NOT NULL,
    AVERAGE_PRICE DECIMAL(11,2) NOT NULL,
    USED_TIME DATETIME,
    UNIQUE (USERNAME)
) ENGINE = INNODB, COLLATE = utf8_general_ci;

CREATE TABLE sellercategory (
    PK INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SELLER INT UNSIGNED NOT NULL,
    SUB_CATEGORY INT UNSIGNED NOT NULL,
    QUANTITY INT NOT NULL,
    FOREIGN KEY (SELLER) REFERENCES sellers(PK) ON UPDATE CASCADE,
    FOREIGN KEY (SUB_CATEGORY) REFERENCES goodscategoryleveltwo(PK) ON UPDATE CASCADE
) ENGINE = INNODB, COLLATE = utf8_general_ci;
